In [1]:
import pandas as pd
import numpy as np

from sqlalchemy import create_engine

In [2]:
path_to_db = '/datasets/telecomm_csi.db'
engine = create_engine(f'sqlite:///{path_to_db}', echo = False)

In [3]:
query = """
SELECT  user_id,lt_day,
        CASE
    WHEN lt_day <= 365 THEN 'yes'
    ELSE 'no'
       END as is_new,
age,
CASE 
    WHEN gender_segment = 0 THEN 'male'
    ELSE 'female'
        END as gender_segment,

os_name,cpe_type_name,location.country,location.city,age_segment.title as age_segment,
traffic_segment.title as traffic_segment,lifetime_segment.title as lifetime_segment,nps_score,
CASE
    WHEN nps_score < 7 THEN 'detractors'
    WHEN nps_score <= 8 AND nps_score < 9 THEN 'passives'
    WHEN nps_score <= 10 THEN  'promoters'
       END as nps_group

FROM user as user
LEFT JOIN location on location.location_id = user.location_id
LEFT JOIN age_segment on age_segment.age_gr_id = user.age_gr_id
LEFT JOIN traffic_segment on traffic_segment.tr_gr_id = user.tr_gr_id
LEFT JOIN lifetime_segment on lifetime_segment.lt_gr_id  = user.lt_gr_id
"""

In [4]:
df = pd.read_sql(query, engine)
df.head(20)

,user_id,lt_day,is_new,age,gender_segment,os_name,cpe_type_name,country,city,age_segment,traffic_segment,lifetime_segment,nps_score,nps_group
0,A001A2,2320,no,45.0,female,ANDROID,SMARTPHONE,Россия,Уфа,05 45-54,04 1-5,08 36+,10,promoters
1,A001WF,2344,no,53.0,male,ANDROID,SMARTPHONE,Россия,Киров,05 45-54,04 1-5,08 36+,10,promoters
2,A003Q7,467,no,57.0,male,ANDROID,SMARTPHONE,Россия,Москва,06 55-64,08 20-25,06 13-24,10,promoters
3,A004TB,4190,no,44.0,female,IOS,SMARTPHONE,Россия,РостовнаДону,04 35-44,03 0.1-1,08 36+,10,promoters
4,A004XT,1163,no,24.0,male,ANDROID,SMARTPHONE,Россия,Рязань,02 16-24,05 5-10,08 36+,10,promoters
5,A005O0,5501,no,42.0,female,ANDROID,SMARTPHONE,Россия,Омск,04 35-44,05 5-10,08 36+,6,detractors
6,A0061R,1236,no,45.0,male,ANDROID,SMARTPHONE,Россия,Уфа,05 45-54,06 10-15,08 36+,10,promoters
7,A009KS,313,yes,35.0,male,ANDROID,SMARTPHONE,Россия,Москва,04 35-44,13 45-50,05 7-12,10,promoters
8,A00AES,3238,no,36.0,female,ANDROID,SMARTPHONE,Россия,СанктПетербург,04 35-44,04 1-5,08 36+,10,promoters
9,A00F70,4479,no,54.0,female,ANDROID,SMARTPHONE,Россия,Волгоград,05 45-54,07 15-20,08 36+,9,promoters
10,A00HL5,5297,no,39.0,male,ANDROID,SMARTPHONE,Россия,Тольятти,04 35-44,09 25-30,08 36+,10,promoters
11,A00NDN,1374,no,21.0,male,ANDROID,SMARTPHONE,Россия,Рязань,02 16-24,06 10-15,08 36+,2,detractors
12,A00P46,179,yes,27.0,male,ANDROID,SMARTPHONE,Россия,Казань,03 25-34,13 45-50,04 4-6,10,promoters
13,A00SA7,667,no,60.0,male,ANDROID,TABLET,Россия,Казань,06 55-64,05 5-10,06 13-24,5,detractors
14,A00U8A,2908,no,44.0,female,ANDROID,SMARTPHONE,Россия,СанктПетербург,04 35-44,05 5-10,08 36+,10,promoters
15,A0116Q,2517,no,34.0,male,ANDROID,SMARTPHONE,Россия,Самара,03 25-34,07 15-20,08 36+,10,promoters
16,A015CX,4073,no,47.0,male,ANDROID,SMARTPHONE,Россия,Самара,05 45-54,12 40-45,08 36+,9,promoters
17,A017L3,372,no,37.0,male,IOS,SMARTPHONE,Россия,Красноярск,04 35-44,05 5-10,06 13-24,10,promoters
18,A017QF,6155,no,42.0,female,ANDROID,SMARTPHONE,Россия,Екатеринбург,04 35-44,05 5-10,08 36+,8,passives
19,A018WZ,709,no,43.0,male,ANDROID,SMARTPHONE,Россия,Калуга,04 35-44,08 20-25,06 13-24,10,promoters

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 502493 entries, 0 to 502492
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   user_id           502493 non-null  object
 1   lt_day            502493 non-null  int64
 2   is_new            502493 non-null  object
 3   age               501939 non-null  float64
 4   gender_segment    502493 non-null  object
 5   os_name           502493 non-null  object
 6   cpe_type_name     502493 non-null  object
 7   country           502493 non-null  object
 8   city              502493 non-null  object
 9   age_segment       502493 non-null  object
 10  traffic_segment   502493 non-null  object
 11  lifetime_segment  502493 non-null  object
 12  nps_score         502493 non-null  int64
 13  nps_group         502493 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 53.7+ MB

In [6]:
df.loc[df['age'].isnull()]

,user_id,lt_day,is_new,age,gender_segment,os_name,cpe_type_name,country,city,age_segment,traffic_segment,lifetime_segment,nps_score,nps_group
751,A1E59W,4055,no,NaN,female,ANDROID,SMARTPHONE,Россия,Екатеринбург,08 n/a,04 1-5,08 36+,1,detractors
1209,A28ZDT,4243,no,NaN,female,ANDROID,SMARTPHONE,Россия,Хабаровск,08 n/a,04 1-5,08 36+,5,detractors
1321,A2GLPQ,2354,no,NaN,female,ANDROID,SMARTPHONE,Россия,Иркутск,08 n/a,06 10-15,08 36+,1,detractors
2163,A41C1K,557,no,NaN,female,ANDROID,SMARTPHONE,Россия,РостовнаДону,08 n/a,04 1-5,06 13-24,3,detractors
2667,A513VG,4705,no,NaN,female,IOS,SMARTPHONE,Россия,Екатеринбург,08 n/a,23 95-100,08 36+,9,promoters
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499598,ZUDYU9,520,no,NaN,female,ANDROID,SMARTPHONE,Россия,СанктПетербург,08 n/a,24 100+,06 13-24,9,promoters
500834,ZWQJRW,220,yes,NaN,male,ANDROID,SMARTPHONE,Россия,Самара,08 n/a,03 0.1-1,05 7-12,1,detractors
501246,ZXK9AK,3550,no,NaN,female,ANDROID,SMARTPHONE,Россия,Томск,08 n/a,04 1-5,08 36+,4,detractors
502376,ZZRS2G,345,yes,NaN,male,ANDROID,SMARTPHONE,Россия,Москва,08 n/a,04 1-5,05 7-12,5,detractors
502455,ZZXH2T,268,yes,NaN,female,ANDROID,SMARTPHONE,Россия,Череповец,08 n/a,07 15-20,05 7-12,1,detractors

In [7]:
df.to_csv('telecomm_csi_tableau.csv', index=False)

### Ссылка на дашборд на сайте Tableau Public:

https://clck.ru/323wWT

### Ссылка на pdf-файл с презентацией:

https://docs.google.com/presentation/d/1O_o_oR2JNSZCG0dqe3Ye9QOeIU4zlIRJClvh4jAHE4s/edit?usp=sharing